### ISSUE TITLE
Feedback on design

### ISSUE THREAD

**Issue by tdurand** [opendatacam/opendatacam-website#1]
Really nice style, really like it ! 

![DesktopHD](https://user-images.githubusercontent.com/533590/60191694-0836ab80-9835-11e9-93d9-cf5d50b5ac18.jpg)

I know that content isn't finished but:

- Besides Jetsons, we need also to add Cloud on file or IP cam + Desktop nvidia gpu support mention in the "Local development" section

- Pricing of Xavier and TX2 got a big discount (they also announced another xavier with less RAM..): https://devtalk.nvidia.com/default/topic/1055629/announcements/new-jetson-software-modules-and-pricing/

The Jetson AGX Xavier Developer Kit is now available for a new price of $699.
The Jetson TX2 Developer Kit is now available for $399.

**Comment by tdurand** [comment]
@mmmmmmmmmmmmmmmm @rraapphhaaeell  I'm working on the website today.. If you have already a signifant change in layout from this early version, please send me the sketch file

**Comment by mmmmmmmmmmmmmmmm** [comment]
@tdurand I added the content Raphael wrote down. There are a few changes in the layout, but not much.

![ODC](https://user-images.githubusercontent.com/12696639/60887807-8a6f9880-a255-11e9-8db1-497ff78e0f6d.jpg)

I also just saw that Notion (https://www.notion.so) has a live demo on their website. Would be nice to have ours in a similar way.

<img width="1198" alt="Screen Shot 2019-07-09 at 13 11 10" src="https://user-images.githubusercontent.com/12696639/60887835-98251e00-a255-11e9-9d46-d692c72b2c59.png">

**Comment by tdurand** [comment]
@mmmmmmmmmmmmmmmm many thanks, yes pretty neat the notion live demo, but for this release I won't have the time to build a nice live demo that works well. see https://github.com/opendatacam/opendatacam/issues/78

**Comment by tdurand** [comment]
Will do a simple video screencast, and keep in mind this nice live demo for later

**Comment by tdurand** [comment]
Closing in favor of #3 3
