### ISSUE TITLE
Docker Hub for website image

### ISSUE THREAD

**Issue by florianporada** [opendatacam/opendatacam-website#12]
Hey @tdurand ,

is it possible that I get access to the DockerHub account of odc?
I'm preparing the update for the website and adding a little github actions pipeline.
I would like to use the official odc docker account to host the image there if this is ok.

cc: @b-g

**Comment by tdurand** [comment]
yes, I send you the info by email..

**Comment by tdurand** [comment]
please ping me on tibo.durand [at] gmail , I'm not sure I have your non moovel email
