### ISSUE TITLE
Add github actions and switch to opendata.cam as primary domain

### ISSUE THREAD

**Issue by florianporada** [opendatacam/opendatacam-website#13]
I'm working on the github actions integration right now. The website will be hosted on my digital ocean drop for now. 
It will be available on opendatacam.florianporada.com during dev. (soon) 
Just to keep you in the loop.

cc: @b-g , @tdurand

**Comment by tdurand** [comment]
Hi Florian

Thanks for you effort, but shouldn't we just use Github pages for this ? The website can be exported as static .. and this way it is free to host..

**Comment by tdurand** [comment]
@florianporada Had a little bit of time this morning and just setup the Github page for the website . you can see it deployed here: https://opendatacam.github.io/opendatacam-website/   .. Every time we do `npm run export` and git push it will deploy the `docs` folder.

Now we just would need to setup the custom domain in the settings and add the CNAME file at the root of the repository: https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site

Let me know

**Comment by florianporada** [comment]
Hey Tibo, 

we can do that as well. 
Since I'm migrating the other lab projects in the same way (with github actions and so on). It was basically just copy paste for me. :) 
But you're right regarding the hosting costs.

**Comment by tdurand** [comment]
Yes also it will be easier for maintenance also.. let me know if you need help to setup the CNAME file.. also ping me on my email if you want to move the domain to my company so you don't have to pay for it

**Comment by florianporada** [comment]
The redirect is now in place. So it works besides a little certificate error but this should be gone in a few hours. 
I'll also remove the github actions files so it will not build on every push to master. 
The domain is valid until 2021 and already paid for so it can stay on my account for now.

**Comment by tdurand** [comment]
great ! many thanks !
