### ISSUE TITLE
First version of website 😎😎

### ISSUE THREAD

**Issue by tdurand** [opendatacam/opendatacam-website#3]
Hey there, worked on the website yesterday and today, got to a good state, I won't be able to work more on it before next week, so this gives you the time to finish content.

### Current status:

https://out-sagkjtmrag.now.sh/

It should be responsive down to 320px (Iphone 5), but let me know if you encounter some issues.

### Features / Content

- Menu or not menu ? I feel for this amount of content we may no need to have a menu (the one that would got fixed as we scroll), let me know...
- Footer isn't done now, @b-g told me that it was "in-progress"
- Need to work on a proper demo screencast for both website / github .. I won't be able to deliver this as I will be on the go next week and won't have access to jetsons, I've done a quick one: https://vimeo.com/346340651/38966dac9d , but maybe @florianporada can do better ? then you can just replace the video file on vimeo

### Seo / Google analytics:

for @rraapphhaaeell 

In Layout.js, update those vars

```
const title = `Opendatacam`
const description = `An Open Source Camera to Collect Your Spatial Data`
const urlSiteImage = `static/seo/seo.jpg`
```

Google analytics TODO @tdurand

### Deployment notes

@florianporada , there is a npm task that does a build and a static export to the out directory , you feel free to use this or to just host the node.js app... Please also don't forget to set the ROOT_URL env variable on the docker image.. Also feel free to merge your PR for this ;-) 

In both case, would be good need to enable gzip ( or brotly) on the deployment side of things, if you host the node.js app I can enable it but it's considered bad practice now, better to do it on the nginx / front you'll use..

### Development notes:

In case you want to do small tweaks..

The main is in /pages/index.js , I use https://tailwindcss.com for most of the styling.. it's super fast to work with and fits well for this kind of small project. On production build it removes all the unused css to keep the minimum

When we will replace images, don't forget to use imageOptim or https://squoosh.app before copy pasting them to the /static directory to make them more lightweights

Regenerate favicons with https://realfavicongenerator.net/

**Comment by tdurand** [comment]
_PS: just though that I can still do better screencast next week if needed with simulation mode.._

**Comment by florianporada** [comment]
@tdurand I'm testing the deployment on our env but it seems that all the assets (js and css) still point have the `absolute` paths. Is it possible to change this in the config? maybe just without the first `/`

```
<link rel="preload" href="/_next/static/b95hjKNLYTDEYH87VKH0e/pages/_app.js" as="script"/>
```

**Comment by florianporada** [comment]
Nevermind, got it working by adding: 

```
const isProd = process.env.NODE_ENV === 'production';

module.export = {
  ...
  assetPrefix: isProd ? './' : ''
} 
```

in `next.config.js`

**Comment by tdurand** [comment]
@all well done on the website ! Gifs looks nice and video is super great !

@rraapphhaaeell I just added Google analytics who was missing , please edit the google analytics ID in Layout.js : https://github.com/opendatacam/opendatacam-website/blob/master/components/Layout.js#L18

**Comment by rraapphhaaeell** [comment]
This actually touches upon a bigger challenge. As all other project this page will also live in the blabla.com/projects/opendatacam-v2  we might have to switch to gtag.js ... I'll investigate with @florianporada and it accordingly.

**Comment by tdurand** [comment]
@rraapphhaaeell  Did you solve the Google analytics issue ?

Also I noticed that the text below beat the traffic isn't the correct one.

**Comment by tdurand** [comment]
Congrats on publishing, closing this
