### ISSUE TITLE
Link https://opendata.cam not working

### ISSUE THREAD

**Issue by tdurand** [opendatacam/opendatacam-website#7]
Hi !

Congrats for launch 🙌

I noticed that the https://opendata.cam is not working, only http://opendata.cam does.

Would be nice to fix this because for example on https://github.com/opendatacam/opendatacam we link to the https one and it seems to be dead.

**Comment by florianporada** [comment]
Thanks @tdurand  :) .
There is now SSL cert yet. 
We have to evaluate if we need one since we redirect everything to move-lab.com/project/opendatacam

**Comment by florianporada** [comment]
FYI: SSL cert is on the way 😬✌️
