### ISSUE TITLE
Seo image

### ISSUE THREAD

**Issue by tdurand** [opendatacam/opendatacam-website#8]
Hi again, noticed an other thing when you test the seo tags with Card validator: https://cards-dev.twitter.com/validator

No seo image are picked up because of the sub url the project is on, in the dom we have:

```html
<meta property="og:url" content="https://" class="next-head">
<meta name="twitter:image" content="static/seo/seo.jpg" class="next-head">
```

where we should have absolute url (the og:image doesn't work with relative url infortunately)

```html
<meta property="og:url" content="https://www.move-lab.com/project/opendatacam" class="next-head">
<meta name="og:image" content="https://www.move-lab.com/project/opendatacam/static/seo/seo.jpg" class="next-head">
```

@florianporada A quick fix would be to hardcode the correct values in https://github.com/opendatacam/opendatacam-website/blob/master/components/Layout.js , https://github.com/opendatacam/opendatacam-website/blob/master/components/Layout.js#L12 

Or I can do a quick PR which would set the correct value if ROOT_URL and URL_PREFIX are correctly set in env vars or in next.config.js

**Comment by florianporada** [comment]
Let's hard code it for the meta tags since the url will not change - i'll add it

**Comment by tdurand** [comment]
Ok , yes best way please close this issue and the PR once done !
